# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee_email_workshop_uuid_association',
            name='attendee_utsa_id',
            field=models.CharField(default='abc123', max_length=6),
        ),
    ]
