# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee_email_workshop_uuid_association',
            name='attendee_local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='importing.attendee'),
        ),
        migrations.AlterField(
            model_name='attendee_email_workshop_uuid_association',
            name='workshop_local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='importing.workshop'),
        ),
    ]
