# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0003_auto_20171106_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee_email_workshop_uuid_association',
            name='workshop_local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workshops.Workshop'),
        ),
    ]
