# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0003_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='has_been_emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='utsa_id',
            field=models.CharField(default='abc123', max_length=6),
        ),
    ]
