# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0004_auto_20171007_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='has_been_emailed',
        ),
    ]
