# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0005_remove_attendee_has_been_emailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(default='title', max_length=48)),
                ('session_date', models.CharField(default='5 November', max_length=48)),
                ('session_threshold', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='utsa_id',
            field=models.CharField(default='abc123', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sessions',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='importing.session'),
            preserve_default=False,
        ),
    ]
