# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0006_auto_20171106_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='sessions',
        ),
    ]
