# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0003_auto_20171106_1936'),
        ('importing', '0007_remove_workshop_sessions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='session',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='workshop',
        ),
    ]
