# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=45)),
                ('email_body', models.CharField(max_length=2000)),
                ('email_signature', models.CharField(max_length=45)),
            ],
        ),
    ]
