# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(default='name', max_length=16)),
                ('email_subject', models.CharField(default='subject', max_length=48)),
                ('email_body', models.TextField(default='body', max_length=2000)),
                ('email_signature', models.CharField(default='jumpstartutsa@gmail.com', max_length=48)),
            ],
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='survery_title',
            new_name='survey_title',
        ),
    ]
