# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0002_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='email',
            new_name='email_template',
        ),
    ]
