# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0003_auto_20170930_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='email_name',
            field=models.CharField(default='name', max_length=16),
        ),
        migrations.AlterField(
            model_name='email_template',
            name='email_body',
            field=models.CharField(default='body', max_length=2000),
        ),
        migrations.AlterField(
            model_name='email_template',
            name='email_signature',
            field=models.CharField(default='jumpstartutsa@gmail.com', max_length=45),
        ),
        migrations.AlterField(
            model_name='email_template',
            name='email_subject',
            field=models.CharField(default='subject', max_length=45),
        ),
    ]
