# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0004_auto_20170930_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='survery_title',
            new_name='survey_title',
        ),
    ]
