# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_scale', models.CharField(choices=[(1, 'No Knowledge'), (2, 'Very little Knowledge'), (3, 'Some'), (4, 'Familiar'), (5, 'Experienced')], default=3, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('creator', models.CharField(max_length=60)),
                ('threshold', models.FloatField(max_length=3)),
                ('pub_date', models.DateField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.Workshop')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.Survey'),
        ),
        migrations.AddField(
            model_name='answeredquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.Question'),
        ),
    ]
