# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateTimeField(default='1987-01-01 00:00'),
        ),
    ]
