# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0001_initial'),
        ('workshops', '0003_auto_20171211_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='registered_attendees',
            field=models.ManyToManyField(to='importing.attendee'),
        ),
    ]
