# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('department', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survery_title', models.CharField(max_length=45)),
                ('survey_body_information', models.CharField(max_length=1000)),
                ('attendees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importing.attendee')),
            ],
        ),
    ]
