# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendee_email_workshop_uuid_association',
            fields=[
                ('uuid_token_local', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendee_clicked_link_local', models.BooleanField(default=False)),
                ('attendee_local', models.ForeignKey(default='wsl_local_string_temp', on_delete=django.db.models.deletion.CASCADE, to='importing.attendee')),
                ('workshop_local', models.ForeignKey(default='wsl_local_string_temp', on_delete=django.db.models.deletion.CASCADE, to='importing.workshop')),
            ],
        ),
    ]
